export const prescriptionTypes = {
  REGISTER_PRESCRIPTION_REQUEST: "./prescription/REGISTER_PRESCRIPTION_REQUEST",
  REGISTER_PRESCRIPTION_SUCCESS: "./prescription/REGISTER_PRESCRIPTION_SUCCESS",
  REGISTER_PRESCRIPTION_FAILURE: "./prescription/REGISTER_PRESCRIPTION_FAILURE",
};
