export const suppliersTypes = {
  GET_SUPPLIER_LIST_REQUEST: "./suppliers/GET_SUPPLIER_LIST_REQUEST",
  GET_SUPPLIER_LIST_SUCCESS: "./suppliers/GET_SUPPLIER_LIST_SUCCESS",
  GET_SUPPLIER_LIST_FAILURE: "./suppliers/GET_SUPPLIER_LIST_FAILURE",

  GET_SUPPLIER_BY_ID_REQUEST: "./suppliers/GET_SUPPLIER_BY_ID_REQUEST",
  GET_SUPPLIER_BY_ID_SUCCESS: "./suppliers/GET_SUPPLIER_BY_ID_SUCCESS",
  GET_SUPPLIER_BY_ID_FAILURE: "./suppliers/GET_SUPPLIER_BY_ID_FAILURE",
  GET_SUPPLIER_BY_ID_CLEAN: "./suppliers/GET_SUPPLIER_BY_ID_CLEAN",

  REGISTER_SUPPLIER_REQUEST: "./suppliers/REGISTER_SUPPLIER_REQUEST",
  REGISTER_SUPPLIER_SUCCESS: "./suppliers/REGISTER_SUPPLIER_SUCCESS",
  REGISTER_SUPPLIER_FAILURE: "./suppliers/REGISTER_SUPPLIER_FAILURE",

  EDIT_SUPPLIER_REQUEST: "./suppliers/EDIT_SUPPLIER_REQUEST",
  EDIT_SUPPLIER_SUCCESS: "./suppliers/EDIT_SUPPLIER_SUCCESS",
  EDIT_SUPPLIER_FAILURE: "./suppliers/EDIT_SUPPLIER_FAILURE",

  DELETE_SUPPLIER_REQUEST: "./suppliers/DELETE_SUPPLIER_REQUEST",
  DELETE_SUPPLIER_SUCCESS: "./suppliers/DELETE_SUPPLIER_SUCCESS",
  DELETE_SUPPLIER_FAILURE: "./suppliers/DELETE_SUPPLIER_FAILURE",
};
