export const doctorTypes = {
  GET_DOCTOR_LIST_REQUEST: "./doctor/GET_DOCTOR_LIST_REQUEST",
  GET_DOCTOR_LIST_SUCCESS: "./doctor/GET_DOCTOR_LIST_SUCCESS",
  GET_DOCTOR_LIST_FAILURE: "./doctor/GET_DOCTOR_LIST_FAILURE",

  REGISTER_DOCTOR_REQUEST: "./doctor/REGISTER_DOCTOR_REQUEST",
  REGISTER_DOCTOR_SUCCESS: "./doctor/REGISTER_DOCTOR_SUCCESS",
  REGISTER_DOCTOR_FAILURE: "./doctor/REGISTER_DOCTOR_FAILURE",

  EDIT_DOCTOR_REQUEST: "./doctor/EDIT_DOCTOR_REQUEST",
  EDIT_DOCTOR_SUCCESS: "./doctor/EDIT_DOCTOR_SUCCESS",
  EDIT_DOCTOR_FAILURE: "./doctor/EDIT_DOCTOR_FAILURE",

  DELETE_DOCTOR_REQUEST: "./doctor/DELETE_DOCTOR_REQUEST",
  DELETE_DOCTOR_SUCCESS: "./doctor/DELETE_DOCTOR_SUCCESS",
  DELETE_DOCTOR_FAILURE: "./doctor/DELETE_DOCTOR_FAILURE",
};
