export const materialsTypes = {
  GET_MATERIAL_LIST_REQUEST: "./customers/GET_MATERIAL_LIST_REQUEST",
  GET_MATERIAL_LIST_SUCCESS: "./customers/GET_MATERIAL_LIST_SUCCESS",
  GET_MATERIAL_LIST_FAILURE: "./customers/GET_MATERIAL_LIST_FAILURE",

  GET_MATERIAL_BY_ID_REQUEST: "./customers/GET_MATERIAL_BY_ID_REQUEST",
  GET_MATERIAL_BY_ID_SUCCESS: "./customers/GET_MATERIAL_BY_ID_SUCCESS",
  GET_MATERIAL_BY_ID_FAILURE: "./customers/GET_MATERIAL_BY_ID_FAILURE",
  GET_MATERIAL_BY_ID_CLEAN: "./customers/GET_MATERIAL_BY_ID_CLEAN",

  REGISTER_MATERIAL_REQUEST: "./customers/REGISTER_MATERIAL_REQUEST",
  REGISTER_MATERIAL_SUCCESS: "./customers/REGISTER_MATERIAL_SUCCESS",
  REGISTER_MATERIAL_FAILURE: "./customers/REGISTER_MATERIAL_FAILURE",

  EDIT_MATERIAL_REQUEST: "./customers/EDIT_MATERIAL_REQUEST",
  EDIT_MATERIAL_SUCCESS: "./customers/EDIT_MATERIAL_SUCCESS",
  EDIT_MATERIAL_FAILURE: "./customers/EDIT_MATERIAL_FAILURE",
};
