export const customersTypes = {
  GET_CUSTOMER_LIST_REQUEST: "./customers/GET_CUSTOMER_LIST_REQUEST",
  GET_CUSTOMER_LIST_SUCCESS: "./customers/GET_CUSTOMER_LIST_SUCCESS",
  GET_CUSTOMER_LIST_FAILURE: "./customers/GET_CUSTOMER_LIST_FAILURE",

  GET_CUSTOMER_BY_ID_REQUEST: "./customers/GET_CUSTOMER_BY_ID_REQUEST",
  GET_CUSTOMER_BY_ID_SUCCESS: "./customers/GET_CUSTOMER_BY_ID_SUCCESS",
  GET_CUSTOMER_BY_ID_FAILURE: "./customers/GET_CUSTOMER_BY_ID_FAILURE",
  GET_CUSTOMER_BY_ID_CLEAN: "./customers/GET_CUSTOMER_BY_ID_CLEAN",

  REGISTER_CUSTOMER_REQUEST: "./customers/REGISTER_CUSTOMER_REQUEST",
  REGISTER_CUSTOMER_SUCCESS: "./customers/REGISTER_CUSTOMER_SUCCESS",
  REGISTER_CUSTOMER_FAILURE: "./customers/REGISTER_CUSTOMER_FAILURE",

  EDIT_CUSTOMER_REQUEST: "./customers/EDIT_CUSTOMER_REQUEST",
  EDIT_CUSTOMER_SUCCESS: "./customers/EDIT_CUSTOMER_SUCCESS",
  EDIT_CUSTOMER_FAILURE: "./customers/EDIT_CUSTOMER_FAILURE",

  DELETE_CUSTOMER_REQUEST: "./customers/DELETE_CUSTOMER_REQUEST",
  DELETE_CUSTOMER_SUCCESS: "./customers/DELETE_CUSTOMER_SUCCESS",
  DELETE_CUSTOMER_FAILURE: "./customers/DELETE_CUSTOMER_FAILURE",
};
