export const productsTypes = {
  GET_PRODUCT_LIST_REQUEST: "./customers/GET_PRODUCT_LIST_REQUEST",
  GET_PRODUCT_LIST_SUCCESS: "./customers/GET_PRODUCT_LIST_SUCCESS",
  GET_PRODUCT_LIST_FAILURE: "./customers/GET_PRODUCT_LIST_FAILURE",

  GET_PRODUCT_BY_ID_REQUEST: "./customers/GET_PRODUCT_BY_ID_REQUEST",
  GET_PRODUCT_BY_ID_SUCCESS: "./customers/GET_PRODUCT_BY_ID_SUCCESS",
  GET_PRODUCT_BY_ID_FAILURE: "./customers/GET_PRODUCT_BY_ID_FAILURE",
  GET_PRODUCT_BY_ID_CLEAN: "./customers/GET_PRODUCT_BY_ID_CLEAN",

  REGISTER_PRODUCT_REQUEST: "./customers/REGISTER_PRODUCT_REQUEST",
  REGISTER_PRODUCT_SUCCESS: "./customers/REGISTER_PRODUCT_SUCCESS",
  REGISTER_PRODUCT_FAILURE: "./customers/REGISTER_PRODUCT_FAILURE",

  EDIT_PRODUCT_REQUEST: "./customers/EDIT_PRODUCT_REQUEST",
  EDIT_PRODUCT_SUCCESS: "./customers/EDIT_PRODUCT_SUCCESS",
  EDIT_PRODUCT_FAILURE: "./customers/EDIT_PRODUCT_FAILURE",
};
