export const patientTypes = {
  GET_PATIENT_LIST_REQUEST: "./patient/GET_PATIENT_LIST_REQUEST",
  GET_PATIENT_LIST_SUCCESS: "./patient/GET_PATIENT_LIST_SUCCESS",
  GET_PATIENT_LIST_FAILURE: "./patient/GET_PATIENT_LIST_FAILURE",

  GET_PATIENT_BY_ID_REQUEST: "./patient/GET_PATIENT_BY_ID_REQUEST",
  GET_PATIENT_BY_ID_SUCCESS: "./patient/GET_PATIENT_BY_ID_SUCCESS",
  GET_PATIENT_BY_ID_FAILURE: "./patient/GET_PATIENT_BY_ID_FAILURE",
  GET_PATIENT_BY_ID_CLEAN: "./patient/GET_PATIENT_BY_ID_CLEAN",

  REGISTER_PATIENT_REQUEST: "./patient/REGISTER_PATIENT_REQUEST",
  REGISTER_PATIENT_SUCCESS: "./patient/REGISTER_PATIENT_SUCCESS",
  REGISTER_PATIENT_FAILURE: "./patient/REGISTER_PATIENT_FAILURE",

  EDIT_PATIENT_REQUEST: "./patient/EDIT_PATIENT_REQUEST",
  EDIT_PATIENT_SUCCESS: "./patient/EDIT_PATIENT_SUCCESS",
  EDIT_PATIENT_FAILURE: "./patient/EDIT_PATIENT_FAILURE",
};
