export const ordersTypes = {
  GET_ORDER_LIST_REQUEST: "./orders/GET_ORDER_LIST_REQUEST",
  GET_ORDER_LIST_SUCCESS: "./orders/GET_ORDER_LIST_SUCCESS",
  GET_ORDER_LIST_FAILURE: "./orders/GET_ORDER_LIST_FAILURE",

  GET_ORDER_BY_ID_REQUEST: "./orders/GET_ORDER_BY_ID_REQUEST",
  GET_ORDER_BY_ID_SUCCESS: "./orders/GET_ORDER_BY_ID_SUCCESS",
  GET_ORDER_BY_ID_FAILURE: "./orders/GET_ORDER_BY_ID_FAILURE",
  GET_ORDER_BY_ID_CLEAN: "./orders/GET_ORDER_BY_ID_CLEAN",

  UPDATE_ORDER_BY_ID_REQUEST: "./orders/UPDATE_ORDER_BY_ID_REQUEST",
  UPDATE_ORDER_BY_ID_SUCCESS: "./orders/UPDATE_ORDER_BY_ID_SUCCESS",
  UPDATE_ORDER_BY_ID_FAILURE: "./orders/UPDATE_ORDER_BY_ID_FAILURE",

  REGISTER_ORDER_REQUEST: "./orders/REGISTER_ORDER_REQUEST",
  REGISTER_ORDER_SUCCESS: "./orders/REGISTER_ORDER_SUCCESS",
  REGISTER_ORDER_FAILURE: "./orders/REGISTER_ORDER_FAILURE",

  EDIT_ORDER_REQUEST: "./orders/EDIT_ORDER_REQUEST",
  EDIT_ORDER_SUCCESS: "./orders/EDIT_ORDER_SUCCESS",
  EDIT_ORDER_FAILURE: "./orders/EDIT_ORDER_FAILURE",
};
